#GET http://localhost:3000/api/articles/2

#DELETE http://localhost:3000/api/replies/2/9

#PUT http://localhost:3000/api/articles/101/1234
#Content-Type: application/json
#
#{
#  "title": "update12",
#  "content": "update",
#  "createDate": "2022-05-24",
#  "writer": "mjk"
#}



#GET https://google.com

#
#GET http://localhost:3000/
#GET http://localhost:3000/api/users/me


#POST http://localhost:3000/api/users
#Content-Type: application/json
#
#{
#  "email": "test@mjkk.com",
#  "password": "1234",
#  "nickname": "test",
#  "repeat_password": "1234"
#}

#POST http://localhost:3000/api/articles
#Content-Type: application/json
#
#{
#  "title": "title - json",
#  "content": "content - json"
#}
#POST http://localhost:3000/api/replies/2
#Content-Type: application/json
#
#{
#  "content": ""
#}
#POST http://localhost:3000/api/auth
#Content-Type: application/json
#
#{
#  "email": "mjk@mjkk.com",
#  "password": "1234"
#}
PATCH http://localhost:3000/api/replies/2/3
Content-Type: application/json

{
  "content": "update"
}
